common/urls.py
from django.urls import path

from . import views

app_name = 'common'
urlpatterns=[
    path('pjt_home',views.p_home,name='prohome'),
    path('cust_login',views.c_home,name='cuslog'),
    path('c_signup',views.c_signup,name='custsp'),
    path('seller_login',views.s_home,name='seller'),
    path('seller_signin',views.s_signin,name='sellersu'),
    path('exist_email',views.email_exist,name='check_email'),
    

]

customer/urls.py
from django.urls import path
from .import views

app_name='customer'
urlpatterns=[
    path('c_home',views.cust_home,name='customer_home'),
    path('profile',views.my_profile,name='myprofile'),
    path('list',views.cat,name='cat_l'),
    path('logout',views.log_out,name='logout_cust'),
    path('ch_pass',views.changepass_cust,name='c_custpass'),
    path('p_detail/<int:pid>',views.product_detail,name='pro_details'),
    path('mycart',views.my_cart,name='cart'),
    path('order',views.my_order,name='myorder'),
    path('remove_cart/<int:pid>',views.remove_item,name='remove_cart'),
    path('master',views.master,name='master'),
    path('purchase/<int:pid>',views.purchase,name='purchase')
    

]

ecommers/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include('common.urls')),
    path('ecom_admin/',include('ecome_admin.urls')),
    path('seller/',include('sellerpage.urls')),
    path('customer/',include('customer.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from sellerpage.models import Product
from common.models import Customer
from datetime import date
# Create your models here.

class Cart(models.Model):
    product_d = models.ForeignKey(Product,on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)


class Order(models.Model):
    customer_id = models.ForeignKey(Customer,on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product,on_delete=models.CASCADE,default='')
    price = models.FloatField()
    status = models.CharField(max_length=30,default='pending')
    seller_id = models.CharField(max_length=40)
    payment_id = models.CharField(max_length=35)


class Order_details(models.Model):
    customer_id = models.ForeignKey(Customer,on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField()
    date = models.DateField(default=date.today)
    status = models.CharField(max_length=30,default='pending')
    payment_id = models.CharField(max_length=35)
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
  

# class Profile(models.Model):
#     profile_pic = models.ImageField(upload_to="product")

customer/views.py
from django.shortcuts import render,redirect
from common.models import Customer, Seller
from sellerpage.models import Product
from .models import Cart, Order, Order_details
from .auth_gaurd import auth_customer

# Create your views here.


@auth_customer
def cust_home(request):
    product_list = Product.objects.all()
    customer_data = Customer.objects.get(id=request.session['customer'])
    return render(request, 'customer/customer_home.html', {'data': customer_data, 'products': product_list})


@auth_customer
def my_profile(request):
    # seller_data = Seller.objects.get(id=request.session['seller'])
    # msg = ''
    # if request.method == 'POST':
    #     product_image = request.FILES['p_file']
    
    customer_data = Customer.objects.get(id=request.session['customer'])
    return render(request, 'customer/profile.html', {'data': customer_data})


@auth_customer
def cat(request):
    product_list = Product.objects.all()
    return render(request, 'customer/catalog.html', {'products': product_list})


@auth_customer
def changepass_cust(request):
    msg = ''
    if request.method == 'POST':
        customer = Customer.objects.get(id = request.session['customer'])

        current_pass = request.POST['cur_pass']
        new_pass = request.POST['new_pass']
        confirm_pass = request.POST['conf_pass']

        if customer.customer_password == current_pass:

            if new_pass == confirm_pass:
                customer.customer_password = new_pass
                customer.save()
                msg = 'password change sucessful'

            else:
                msg = 'password does not match'   

        else:
            msg = 'incorect password'  
    context = {
        'msg':msg
    }              
    return render(request, 'customer/changepassword_cust.html',context)


@auth_customer
def my_cart(request):
    if 'customer' in request.session:  #customer is the key in session where customer login occurs
        # here we create an if 
        product_cart = Cart.objects.filter(customer = request.session['customer'])
        return render(request, 'customer/mycart.html',{'products':product_cart})
    else:
        return redirect('common:cuslog')    


@auth_customer
def product_detail(request, pid):
    product_list = Product.objects.all()
    msg = ''
    product_details = Product.objects.get(id=pid)

    if request.method == 'POST':
        
        #  checking if the user has added the same product in cart
        #  exist() methode return boolen value, tru if data exist , exist function only comes in filter not on get

        product_exist = Cart.objects.filter(product_d = pid,customer = request.session['customer']).exists()

        if not product_exist: # same as 'if product_exist == false'
            cart = Cart(customer_id = request.session['customer'],product_d_id = pid)
            cart.save()
        else:
            msg = 'item alredy add to cart'

        # data we pass views to template is called context data
    context = {
            'details': product_details,
            'msg':msg,
            'products': product_list
        }   
    return render(request, 'customer/productdetail.html',context)


@auth_customer
def remove_item(request,pid):
    cart_item = Cart.objects.get(product_d = pid,customer = request.session['customer'])
    cart_item.delete()
    return redirect('customer:cart')


@auth_customer
def my_order(request):
    # user_id = request.session['customer'] 
    if 'customer' in request.session:  
        order = Order.objects.filter(customer_id = request.session['customer'])
        return render(request, 'customer/myorder.html',{'my_order':order})
    else:
        return redirect('common:cuslog')    


@auth_customer
def log_out(request):
    del request.session['customer']
    request.session.flush() #to remove session from django_session table
    return redirect('common:prohome')


@auth_customer
def master(request):
    pro=Product.objects.all()
    return render(request,'customer/masterpost.html',{'products':pro})


def purchase(request, pid):
    product_list = Product.objects.all()
    msg = ''
    product_details = Product.objects.get(id=pid)   

    if request.method == 'POST':
        

        order_exist = Order.objects.filter(product_id = pid,customer_id = request.session['customer']).exists()

        if not order_exist: 
            order = Order(customer_id_id = request.session['customer'],product_id_id = pid)
            order.save()
        else:
            msg = 'item alredy ordered'
        
    context = {
            'details': product_details,
            'msg':msg,
            'products': product_list
        }   
    return render(request, 'customer/purchase.html',context)
   

customer/templates/customer/catalog.html
{% extends 'customer/customer_home.html' %}

{% block content %}

{% load static %}
<style>
    .ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: inherit;
    align-items: center;
    display: flex;
    justify-content: center;
  }

  .li {
    justify-content: center;
    font-size: larger;
  }

  .li button {
    display: block;
    color: #000000;
    font-weight: 500;
    font-family: Georgia, 'Times New Roman', Times, serif;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    background-color: inherit;
    border: none;
  }
</style>
<!-- <nav>
    <ul>
        <li id="all">all</li>
        <li id="book">books</li>
        <li id="movie">movies</li>
        <li id="game">games</li>
    </ul>
</nav> -->
<div class="nab">
    <div class="row">
        <div class="col-12">
            <ul class="ul">
                <li class="li"><button id="all">all</button></li>
                <li class="li"><button id="book">books</button></li>
                <li class="li"><button id="movie">movies</button></li>
                <li class="li"><button id="game">games</button></li>
            </ul>
        </div>
    </div>
</div>
<div id="al">
    <div class="row">

        {% for product in products %}
        <div class="col-3 ms-4 p-3">
            <div class="card" style="width: 18rem;">
                <a href="{% url 'customer:pro_details' product.id %}"><img src="{{product.product_image.url}}"
                        class="card-img-top" alt="..." style="width:200px; height:200px;"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.product_name|title}}</h5>
                    <h2>Rs.{{product.product_price}}</h2>
                    <!-- <p class="card-text">{{product.product_discription}}</p> -->
                    <p class="card-text">seller:{{product.seller.seller_name}}</p>
                    <a href="{% url 'customer:pro_details' product.id %}" class="btn btn-primary"
                        style="text-decoration: none;">details</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

<div id="bks" style="display: none;">
    <div class="row">

        {% for product in products %}
        {% if product.product_catogari == 'books' %}
        <div class="col-3 ms-4 p-3">
            <div class="card" style="width: 18rem;">
                <a href="{% url 'customer:pro_details' product.id %}"><img src="{{product.product_image.url}}"
                        class="card-img-top" alt="..." style="width:200px; height:200px;"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.product_name|title}}</h5>
                    <h2>Rs.{{product.product_price}}</h2>
                    <!-- <p class="card-text">{{product.product_discription}}</p> -->
                    <p class="card-text">seller:{{product.seller.seller_name}}</p>
                    <a href="{% url 'customer:pro_details' product.id %}" class="btn btn-primary"
                        style="text-decoration: none;">details</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}

    </div>
</div>
<div id="mvs" style="display: none;">
    <div class="row" >

        {% for product in products %}
        {% if product.product_catogari == 'movies' %}
        <div class="col-3 ms-4 p-3">
            <div class="card" style="width: 18rem;">
                <a href="{% url 'customer:pro_details' product.id %}"><img src="{{product.product_image.url}}"
                        class="card-img-top" alt="..." style="width:200px; height:200px;"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.product_name|title}}</h5>
                    <h2>Rs.{{product.product_price}}</h2>
                    <!-- <p class="card-text">{{product.product_discription}}</p> -->
                    <p class="card-text">seller:{{product.seller.seller_name}}</p>
                    <a href="{% url 'customer:pro_details' product.id %}" class="btn btn-primary"
                        style="text-decoration: none;">details</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}

    </div>
</div>
<div id="gms" style="display: none ;">
    <div class="row" >

        {% for product in products %}
        {% if product.product_catogari == 'games' %}
        <div class="col-3 ms-4 p-3">
            <div class="card" style="width: 18rem;">
                <a href="{% url 'customer:pro_details' product.id %}"><img src="{{product.product_image.url}}"
                        class="card-img-top" alt="..." style="width:200px; height:200px;"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.product_name|title}}</h5>
                    <h2>Rs.{{product.product_price}}</h2>
                    <!-- <p class="card-text">{{product.product_discription}}</p> -->
                    <p class="card-text">seller:{{product.seller.seller_name}}</p>
                    <a href="{% url 'customer:pro_details' product.id %}" class="btn btn-primary"
                        style="text-decoration: none;">details</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}

    </div>
</div>
<script>
    var a = document.getElementById('all')
    var b = document.getElementById('book')
    var m = document.getElementById('movie')
    var g = document.getElementById('game')
    console.log(g)
    a.onclick = function () {
        console.log('b')
        document.getElementById('al').style.display = 'block'
        document.getElementById('bks').style.display = 'none'
        document.getElementById('mvs').style.display = 'none'
        document.getElementById('gms').style.display = 'none'

    }
    b.onclick = function () {
        console.log('b')
        document.getElementById('al').style.display = 'none'
        document.getElementById('bks').style.display = 'block'
        document.getElementById('mvs').style.display = 'none'
        document.getElementById('gms').style.display = 'none'

    }
    m.onclick = function () {
        console.log('m')
        document.getElementById('al').style.display = 'none'
        document.getElementById('bks').style.display = 'none'
        document.getElementById('mvs').style.display = 'block'
        document.getElementById('gms').style.display = 'none'

    }
    g.onclick = function () {
        console.log('g')
        document.getElementById('al').style.display = 'none'
        document.getElementById('bks').style.display = 'none'
        document.getElementById('mvs').style.display = 'none'
        document.getElementById('gms').style.display = 'block'

    }






</script>

{% endblock %}

customer/templates/customer/customer_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>customer_home</title>
  <link rel="stylesheet" href="{% static 'css/cut.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  {% block header %}
  
  {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-dark" style="padding: 2%;">
    <div class="container-fluid">
      <a href="{% url 'customer:myprofile' %}"><img src="{% static 'images/ku.jpg' %}" class="admin_img " alt="" style="width: 40px;
    height: 35px;
    border-radius: 100px;"></a>
      <!-- <a class="navbar-brand" href="#"></a> -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customer:customer_home' %}"
              style="color: white;">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'customer:cart' %}" style="color: white;">myCart</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'customer:cat_l' %}" style="color: white;">Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'customer:c_custpass' %}" style="color: white;">change password</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'customer:myorder' %}" style="color: white;">myOrder</a>
          </li>
          <li class=" nav-item">
            <a class="nav-link active" href="{% url 'customer:logout_cust' %}" style="color: white;">logout</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  

  {% block content %}

  <div class="text-center">
    <h1><i>wellcome {{data.customer_name}}</i></h1>
  </div>
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/hp.jpg' %}" class="d-block w-100" alt="..." style="height: 500px; width: 100%;">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Some representative placeholder content for the first slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/z.jpg' %}" class="d-block w-100" alt="..." style="height: 500px; width: 100%;">
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Some representative placeholder content for the second slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/spm.jpg' %}" class="d-block w-100" alt="..." style="height: 500px; width: 100%;">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Some representative placeholder content for the third slide.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="row">
       <b class="text-center"> PRODUCTS</b>
    {% for product in products %}
    <div class="col-3 ms-4 p-2" style="overflow: hidden;">
      <div class="card" style="width: 18rem; height: 18rem;">
        <a href=""><img src="{{product.product_image.url}}" class="card-img-top" alt="..."
            style="width:90px; height:90px;"></a>
        <div class="card-body p-3">
          <h5 class="card-title" style="margin-bottom: 0;">{{product.product_name|title}}</h5>
          <h2 style="margin-bottom: 0;">Rs.{{product.product_price}}</h2>
          <!-- <p class="card-text" style="margin-bottom: 0;overflow: hidden;">{{product.product_discription}}</p> -->
          <p class="card-text" style="margin-bottom: 0;">seller:{{product.seller.seller_name}}</p>
          <a href="{% url 'customer:pro_details' product.id %}" class="btn btn-primary"
            style="text-decoration: none;">details</a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>

  {% endblock %}
  </div>
  </div>
  <footer id="foot_er">
    <div class="row">
      <div class="col-md-3">
        <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a> <br><br>
        <a class="nav-link" href="" style="color: aliceblue;"><b>contact</b></a><br><br>
        <a class="nav-link" href="" style="color: aliceblue;"><b>email@gamil.com</b></a>
      </div>
      <div class="col-md-3">
        <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a>
      </div>
      <div class="col-md-3">
        <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a>
      </div>
    </div>
  
  </footer>
</body>

</html>

customer/templates/customer/masterpost.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>customer_home</title>
    <link rel="stylesheet" href="{% static 'css/cut.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/cut.css' %}">
    {% block header %}

    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-dark" style="padding: 2%;">
        <div class="container-fluid">
            <a href="{% url 'customer:myprofile' %}"><img src="{% static 'images/ku.jpg' %}" class="admin_img " alt=""
                    style="width: 40px;
    height: 35px;
    border-radius: 100px;"></a>
            <!-- <a class="navbar-brand" href="#"></a> -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'customer:customer_home' %}"
                            style="color: white;">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'customer:cart' %}" style="color: white;">myCart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'customer:cat_l' %}" style="color: white;">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'customer:c_custpass' %}" style="color: white;">change
                            password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'customer:myorder' %}" style="color: white;">myOrder</a>
                    </li>
                    <li class=" nav-item">
                        <a class="nav-link active" href="{% url 'customer:logout_cust' %}"
                            style="color: white;">logout</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>


    {% block post %}
    {% endblock %}


    <div class="row" style="margin-top: 3%; margin-bottom: 5%;    ">
        <div class="col-md-12">
            <div class="container" id="space-for">
                <div class="row">
                    <b class="text-center"> PRODUCTS</b>
                    {% for product in products %}
                    <div class="col-md-4 col-12 p-2" style="overflow: hidden;">
                        <div class="card" style="width: 18rem; height: 18rem;">
                            <a href=""><img src="{{product.product_image.url}}" class="card-img-top" alt="..."
                                    style="width:90px; height:90px;"></a>
                            <div class="card-body p-3">
                                <h5 class="card-title" style="margin-bottom: 0;">{{product.product_name|title}}</h5>
                                <h2 style="margin-bottom: 0;">Rs.{{product.product_price}}</h2>
                                <!-- <p class="card-text" style="margin-bottom: 0; overflow: hidden;">{{product.product_discription}}</p> -->
                                <p class="card-text" style="margin-bottom: 0;">seller:{{product.seller.seller_name}}</p>
                                <a href="{% url 'customer:pro_details' product.id %}" class="btn btn-primary"
                                    style="text-decoration: none;">details</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}




                </div>
            </div>

        </div>
    </div>
    <footer id="foot_er">
        <div class="row">
            <div class="col-md-3">
                <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a> <br><br>
                <a class="nav-link" href="" style="color: aliceblue;"><b>contact</b></a><br><br>
                <a class="nav-link" href="" style="color: aliceblue;"><b>email@gamil.com</b></a>
            </div>
            <div class="col-md-3">
                <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a>
            </div>
            <div class="col-md-3">
                <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a>
            </div>
        </div>

    </footer>
</body>

customer/templates/customer/mycart.html
{% extends 'customer/customer_home.html' %}

{% block content %}

{% load static %}

<div class="container p-4">
    <h2 class="text-center p-4">MY CART</h2>

   <div class="row bg-light">
    {% if products %}
    <table class="table table--striped-colums">
        <tr>
            <th>PRODUCT NAME</th>
            <!-- <th>PRODUCT DISCRIPTION</th> -->
            <th>PRODUCT NUMBER</th>
            <th>PRODUCT STOCK</th>
            <th>PRODUCT IMAGE</th>
            <th>PRODUCT PRICE</th>
            <th>PRODUCT SELLER</th>
            <th>REMOVE</th>
        </tr>
        {% for product_cart in products %}
        <tr>
            <th>{{product_cart.product_d.product_name|title}}</th>
            <!-- <th>{{product_cart.product_d.product_discription}}</th> -->
            <th>{{product_cart.product_d.product_number}}</th>
            <th>{{product_cart.product_d.product_stock}}</th>
            <th><img src="{{product_cart.product_d.product_image.url}}" class="card-img-top" alt="..." style="width:200px; height:200px;"></th>
            <th>{{product_cart.product_d.product_price}}</th>
            <th>{{product_cart.product_d.seller.seller_name}}</th>
            <th><a href="{% url 'customer:remove_cart' product_cart.product_d.id %}"><button class="btn btn-sucess" style="background-color: rgb(207, 50, 50);">REMOVE</button></a></th>
        </tr>
        {% endfor %}
    </table>
    {% else %}

    <h1 style="color: red; text-align: center;"><i>cart empty</i></h1>

    {% endif %}
   </div>
</div>

{% endblock %}

customer/templates/customer/purchase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <nav class="navbar bg-dark" style="background-color: rgb(0, 64, 255); height: 70px;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/ku.jpg' %}" alt="Logo" class="admin_img " style="width: 40px; padding: 10px;
            height: 35px;
            border-radius: 100px;">
        <b style="color: rgb(213, 43, 199); font-size: xx-large;"> <i>VIVELIOGRAFI</i></b>
      </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a class="nav-link active" aria-current="" href="{% url 'customer:customer_home' %}"
        style="color: white;">Home</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a class="nav-link active" aria-current="" href="{% url 'customer:myorder' %}"
        style="color: white;">my order</a>
    </div>
  </nav>
  <div>
    <div
      style="height: 500px; width: 60%; margin-top: 30px; margin-bottom: 50px; margin-right: 50px; margin-left: 130px;">
      <header style="background-color: rgb(18, 65, 234); height: 70px; text-align: center;"> DELIVER</header>
      <label for="" class="form-label text-light">ADDRESS</label><br>
      <input type="text" name="s_companyname" style="width: 100%;height: 30px;" class="form-control" id=""
        aria-describedby=""><br><br>


      <form method="POST">
        {% csrf_token %}
        <button type="submit" class=" btn btn-outline-success" id="btn-link"
          style="background-color:rgb(234, 234, 69);width: 500px;height: 35px;margin-left: 50px;">DELIVER</button>
      </form>
    </div>
  </div>
</body>

</html>