common/urls.py
from django.urls import path

from . import views

app_name = 'common'
urlpatterns=[
    path('pjt_home',views.p_home,name='prohome'),
    path('cust_login',views.c_home,name='cuslog'),
    path('c_signup',views.c_signup,name='custsp'),
    path('seller_login',views.s_home,name='seller'),
    path('seller_signin',views.s_signin,name='sellersu'),
    path('exist_email',views.email_exist,name='check_email'),
    

]

ecome_admin/urls.py
from django.urls import path
from .import views

app_name='ecom_admin'
urlpatterns=[
    path('ecomadmin_home',views.ecomadmin_home,name='ecomadminhome'),
    path('approve_cust',views.approve_cust,name='approvecust'),
    path('approve_seller',views.approve_seller,name='approveseller'),
    path('view_cust',views.view_cust,name='viewcust'),
    path('view_seller',views.view_seller,name='viewseller'),
    path('approve/<int:sid>',views.approve,name='approve'),
    path('deletesell/<int:sid>',views.delete_seller,name='delete_seller'),   
    path('deletecust/<int:sid>',views.delete_cust,name='delete_cust'),    
]

ecommers/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include('common.urls')),
    path('ecom_admin/',include('ecome_admin.urls')),
    path('seller/',include('sellerpage.urls')),
    path('customer/',include('customer.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecome_admin/models.py
from django.db import models

# Create your models here.

ecome_admin/views.py
from django.shortcuts import render,redirect
from common.models import Customer,Seller
from sellerpage.models import Product
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.

def ecomadmin_home(request):
    product = Product.objects.all()
    return render(request,'ecome_admin/admin_home.html',{'product_list':product})

def approve_cust(request):

    customer = Customer.objects.all()

    return render(request,'ecome_admin/approvecust.html',{'customer_list':customer})

def approve_seller(request):
    seller = Seller.objects.all()
    return render(request,'ecome_admin/approveseller.html',{'seller_list':seller})


def view_cust(request):
    cust = Customer.objects.all()
    return render(request,'ecome_admin/view_cust.html',{'cust_list':cust})

def view_seller(request):
    sell = Seller.objects.filter(approved = True)
    return render(request,'ecome_admin/viewseller.html',{'sell_list':sell})

def approve(request,sid):
    seller = Seller.objects.get(id=sid)
    msg = 'you are approved to login'
    send_mail(
        'login approve',
        msg,
        settings.EMAIL_HOST_USER,
        [seller.seller_email,],
    )
    seller.approved = True
    seller.save()
    return redirect('ecom_admin:approveseller')


def delete_seller(request,sid):
    seller_list = Seller.objects.get(id = sid)
    seller_list.delete()
    return redirect('ecom_admin:approveseller')

def delete_cust(request,sid):
    customer_list = Customer.objects.get(id = sid)
    customer_list.delete()
    return redirect('ecom_admin:approvecust')    

ecome_admin/templates/ecome_admin/admin_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin_home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="row">
        <div class="col-md-2 bg-success nav" >
            
            <div>
                <img src="{% static 'images/pp.webp' %}" class="admin_img " alt="" style="width: 200px;
                height: 200px;padding-left: 50px;
                padding-top: 40px;
                border-radius: 100px;">
            </div>

            <div class="">
                <ul class="list text-light" style="padding-left: 60px;
                font-size: larger;
                list-style-type: none;">
                    <li><a href="{% url 'ecom_admin:approvecust' %}" class="li0" style=" text-decoration: none;
                        color: white;">approve_cust</a> </li> <br>
                    <li><a href="{% url 'ecom_admin:approveseller' %}" class="li0" style="text-decoration: none;
                        color: white;">approve_seller </a> </li> <br>
                    <li><a href="{% url 'ecom_admin:viewcust' %}" class="li0" style="text-decoration: none;
                        color: white;">View_Cust </a></li> <br>
                    <li><a href="{% url 'ecom_admin:viewseller' %}" class="li0" style="text-decoration: none;
                        color: white;">View_Seller </a></li> <br>
                </ul>
            </div>
        </div>
        <div class="col-md-10">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>
</html>

ecome_admin/templates/ecome_admin/approvecust.html
{% extends 'ecome_admin/admin_home.html' %}

{% block content %}
    <div class="text-center p-4">
        <h1>APPROVE CUSTOMER</h1>
    </div>
<div class="container">
    <div class="row">
        
        <div class="">
            <table class="table">
                <thead>
                <th>Seller Name</th>
                <th>email</th>
                <!-- <th>Password</th> -->
                <th>address</th>
                <th>gender</th>
                <th>Status</th>
                <th>Remove</th>
                </thead>
                <tbody>
                    {% for customer in customer_list %}
                <tr class="table-active">
                   <td>{{customer.customer_name}}</td>
                   <td>{{customer.customer_email}}</td>
                   <!-- <td>{{customer.customer_password}}</td> -->
                   <td>{{customer.customer_addres}}</td>
                   <td>{{customer.customer_gender}}</td>
                   <td>active</td>
                   <td><button type="button" class="btn btn-danger"><a
                    href="{% url 'ecom_admin:delete_cust' customer.id %}"><b>REMOVE</b></a></button></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>

{% endblock %}

ecome_admin/templates/ecome_admin/approveseller.html
{% extends 'ecome_admin/admin_home.html' %}

{% block content %}
<div class="text-center p-4">
    <h1>APPROVE SELLER</h1>
</div>
<div class="container">
    <div class="row">

        <div class="">
            <table class="table">
                <thead>
                    <th>Seller Name</th>
                    <th>photo</th>
                    <th>Address</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>Company Name</th>
                    <th>Account Holder Name</th>
                    <th>IFSC</th>
                    <th>Account Number</th>
                    <th>Password</th>
                    <th>Status</th>
                    <th>Remove</th>
                </thead>
                <tbody>
                    {% for seller in seller_list %}
                    <tr class="table-active">
                        <td>{{seller.seller_name|title}}</td>
                        <td><img src="{{seller.seller_pic.url}}" alt=""></td>
                        <td>{{seller.seller_addres}}</td>
                        <td>{{seller.seller_phone}}</td>
                        <td>{{seller.seller_email}}</td>
                        <td>{{seller.seller_companyname}}</td>
                        <td>{{seller.seller_accholdername}}</td>
                        <td>{{seller.seller_ifsc}}</td>
                        <td>{{seller.seller_accno}}</td>
                        <td>{{seller.seller_password}}</td>
                        <td>
                            {% if not seller.approved %}
                            <button type="button" class="btn btn-primary"><a
                                    href="{% url 'ecom_admin:approve' seller.id %}">APPROVE</a></button>
                            {% else %}
                            <p style="color: gray;"><b>APPROVE</b></p>
                            {% endif %}
                        </td>
                        <td> 
                            <button type="button" class="btn btn-danger"><a
                                    href="{% url 'ecom_admin:delete_seller' seller.id %}"><b>REMOVE</b></a></button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>
{% endblock %}

ecome_admin/templates/ecome_admin/view_cust.html
{% extends 'ecome_admin/admin_home.html' %}

{% block content %}

    <div class="text-center p-4">
        <h1>VIEW CUSTOMER</h1>
    </div>

    <div class="container">
        <div class="row">
            
            <div class="">
                <table class="table">
                    <thead>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Username</th>
                        <th>Phone Number</th>
                        <th>Address</th>
                        <th>Gender</th>
                        <th>Password</th>
                    
                    </thead>
                    <tbody>
                        {% for customer in cust_list %}
                    <tr class="table-active">
                        <td>{{customer.customer_name}}</td>
                        <td>{{customer.customer_email}}</td>
                        <td>{{customer.customer_username}}</td>
                        <td>{{customer.customer_phone}}</td>
                        <td>{{customer.customer_addres}}</td>
                        <td>{{customer.customer_gender}}</td>
                        <td>{{customer.customer_password}}</td>
                        
                       
                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    
        </div>
    </div>

    {% endblock %}

ecome_admin/templates/ecome_admin/viewseller.html
{% extends 'ecome_admin/admin_home.html' %}

{% block content %}
    <div class="text-center p-4">
        <h1>VIEW SELLER</h1>
    </div>

    <div class="container">
        <div class="row">
            
            <div class="">
                <table class="table">
                    <thead>
                    <th>Seller Name</th>
                    <th>Profile</th>
                    <th>Address</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>Company Name</th>
                    <th>Account Holder Name</th>
                    <th>IFSC</th>
                    <th>Account Number</th>
                    <th>Password</th>
                    
                    </thead>
                    <tbody>
                    
                        {% for seller in sell_list %}
                    <tr class="">
                        <td>{{seller.seller_name}}</td>
                        <td><img src="{{seller.seller_pic.url}}" alt=""></td>
                        <td>{{seller.seller_address}}</td>
                        <td>{{seller.seller_phone}}</td>
                        <td>{{seller.seller_email}}</td>
                        <td>{{seller.seller_companyname}}</td>
                        <td>{{seller.seller_accholdername}}</td>
                        <td>{{seller.seller_ifsc}}</td>
                        <td>{{seller.seller_accno}}</td>
                        <td>{{seller.seller_password}}</td>
                    </tr>
                      {% endfor %}  
                       
                    
                    </tbody>
                </table>
            </div>
    
        </div>
    </div>
    {% endblock %}