common/urls.py
from django.urls import path

from . import views

app_name = 'common'
urlpatterns=[
    path('pjt_home',views.p_home,name='prohome'),
    path('cust_login',views.c_home,name='cuslog'),
    path('c_signup',views.c_signup,name='custsp'),
    path('seller_login',views.s_home,name='seller'),
    path('seller_signin',views.s_signin,name='sellersu'),
    path('exist_email',views.email_exist,name='check_email'),
    

]

customer/urls.py
from django.urls import path
from .import views

app_name='customer'
urlpatterns=[
    path('c_home',views.cust_home,name='customer_home'),
    path('profile',views.my_profile,name='myprofile'),
    path('list',views.cat,name='cat_l'),
    path('logout',views.log_out,name='logout_cust'),
    path('ch_pass',views.changepass_cust,name='c_custpass'),
    path('p_detail/<int:pid>',views.product_detail,name='pro_details'),
    path('mycart',views.my_cart,name='cart'),
    path('order',views.my_order,name='myorder'),
    path('remove_cart/<int:pid>',views.remove_item,name='remove_cart'),
    path('master',views.master,name='master'),
    path('purchase/<int:pid>',views.purchase,name='purchase')
    

]

ecommers/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include('common.urls')),
    path('ecom_admin/',include('ecome_admin.urls')),
    path('seller/',include('sellerpage.urls')),
    path('customer/',include('customer.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    customer_name = models.CharField(max_length=20)
    customer_email = models.CharField(max_length=20)
    customer_password = models.CharField(max_length=10)
    customer_addres = models.CharField(max_length=40,default='')
    customer_gender = models.CharField(max_length=40,default='')


class Seller(models.Model):
    seller_name = models.CharField(max_length=20)
    seller_address = models.CharField(max_length=100)
    seller_phone = models.BigIntegerField()
    seller_email = models.CharField(max_length=30)
    seller_companyname = models.CharField(max_length=20)
    seller_accholdername = models.CharField(max_length=20)
    seller_ifsc = models.CharField(max_length=15)
    seller_branch = models.CharField(max_length=20)
    seller_accno = models.BigIntegerField()
    seller_username = models.CharField(max_length=20)
    seller_password = models.CharField(max_length=20)
    seller_pic = models.ImageField(upload_to='seller/')
    approved = models.BooleanField(default=False)

common/views.py
from django.shortcuts import render, redirect
from .models import Customer, Seller
from sellerpage.models import Product
import random
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse

# Create your views here.


def p_home(request):
    product_list = Product.objects.all()
    return render(request, 'common/project_home.html', {'products': product_list})


def c_home(request):
    mss = ''
    if request.method == 'POST':
        cust_email = request.POST['cust_mail']
        cust_password = request.POST['cust_pass']

        try:
            customer = Customer.objects.get(
                customer_email = cust_email, customer_password = cust_password)
            request.session['customer'] = customer.id  # create a session
            return redirect('customer:customer_home')
        except :
            mss = 'email and password is incorrect'
            return render(request, 'common/cust_login.html', {'mss': mss, })
    return render(request, 'common/cust_login.html')


def c_signup(request):

    if request.method == 'POST':
        cst_name = request.POST['c_name']
        cst_email = request.POST['c_mail']
        cst_password = request.POST['c_pass']
        cst_number = request.POST['nub']
        cst_address = request.POST['c_address']
        cst_gender = request.POST['gender']
        # to insert6 data into table

        # 1.create object of model class eg: customer

        new_customer = Customer(customer_name=cst_name,
                                customer_email=cst_email,
                                customer_password=cst_password,
                                customer_addres=cst_address,
                                customer_gender=cst_gender)

        new_customer.save()

    return render(request, 'common/cust_signup.html')


def s_home(request):
    msg = ''
    if request.method == 'POST':
        user_name = request.POST['u_name']
        pass_word = request.POST['pass']

        try:
            seller = Seller.objects.get(
                seller_username=user_name,  seller_password=pass_word)

        #  if username and password correct,we set a session variable with key 'seller'
        # session variable will be accessed throughout the application

        # working of django session
        # when username and password correct,we set a session variable with key(here key is 'seller') and
        # unique value for each seller (here value is the primary key of the logged in seller)
        # if a seller with primary key 2 logs in, session key will be 'seller' and value will be 2

        # when we set a session, key and value will be stored in django_session table inside database in encrypted from

        # the encrypted key will be sent with http response to the clinte (browser)
        # in the clinte side (browser), the key reciver from the server will be stored in browser storage (cookies in case of django)

        # when the user request any opage (eg : cart page) from the same browser, the sme key stored inside cookies
        # will be send to the server through http request

        # when request reches the server, it will look for the key stored in cookies to match with
        # django_session table inside the database to find the corresponding user

            request.session['seller'] = seller.id  # create a session
            return redirect('sellerpage:sellerhome')
        except:
            msg = 'username and password is incorrect'
    return render(request, 'common/seller_login.html', {'msg': msg, })


def s_signin(request):
    if request.method == 'POST':
        seller_name = request.POST['s_name'].lower()
        seller_address = request.POST['s_address']
        seller_phone = request.POST['s_phone']
        seller_email = request.POST['s_email']
        seller_companyname = request.POST['s_companyname']
        seller_holdername = request.POST['s_accholdername']
        seller_ifsc = request.POST['s_ifsc']
        seller_branch = request.POST['s_branch']
        seller_accno = request.POST['s_accnumber']
        seller_file = request.FILES['s_file']

        seller_username = random.randint(1111, 9999)
        seller_password = 'sel-' + seller_name + str(seller_username)
        message = 'hai your username is ' + \
            str(seller_username) + 'and temporary password is ' + seller_password
        send_mail(
            'username and temporary password',
            message,
            settings.EMAIL_HOST_USER,
            [seller_email,],
            fail_silently=False
        )

        new_seller = Seller(
            seller_name=seller_name,
            seller_address=seller_address,
            seller_email=seller_email,
            seller_phone=seller_phone,
            seller_companyname=seller_companyname,
            seller_accholdername=seller_holdername,
            seller_ifsc=seller_ifsc,
            seller_branch=seller_branch,
            seller_accno=seller_accno,
            seller_pic=seller_file,
            seller_password=seller_password,
            seller_username=seller_username,

        )

        new_seller.save()

    return render(request, 'common/seller_signin.html')

def email_exist(request):
    email = request.POST['email'] # here 'email' is the key in json

    status = Customer.objects.filter(customer_email = email).exists()

    return JsonResponse({'status':status}) 

common/templates/common/cust_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>customer login</title>
    <link rel="stylesheet" href="{% static 'css/pro2.css' %}">
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"></script>
</head>
<body>
    <div>
        <header class="text-center "><h1>CUSTOMER LOGIN</h1></header>
    </div>
    <div class="container p-4">
      <a href="{% url 'common:prohome' %}" style="padding-left: 90%;"><button class="btn-danger"><--HOME--></button></a>
    <div class="cust p-4">
        <form method="POST">
          {% csrf_token %}
          {{mss}}
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">User Email</label>
            <input type="email" name="cust_mail" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
          </div><br>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" name="cust_pass" class="form-control" id="exampleInputPassword1">
            </div><br>
            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button><br>
            <span>sign up if you don't have an account</span><a href="{% url 'common:custsp' %}">sign up</a>
          </form>
    </div>
  </div>
</body>
</html>

common/templates/common/cust_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/pro2.css' %}">
  <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
  <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"></script>
  <script src=" https://code.jquery.com/jquery-3.6.1.js"
    integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous">
  </script>
</head>

<body>
  <div class="sign">
    <a href="{% url 'common:cuslog' %}" style="padding-left: 90%;"><button class="btn btn-primary" style="background-color: darkblue; color: white">LOGIN</button></a>

    <form class="row g-3 p-4" method="POST">
      {% csrf_token %}
      <div class="text-center">
        <header>
          <h2>CUSTOMER SIGN UP</h2>
        </header>
      </div>
      <div class="row p-4">
        <div class="col">
          <input type="text" class="form-control" placeholder="Name" aria-label=" name" name="c_name">
        </div>
      </div>
      <div class="col-md-6">
        <label for="inputEmail4" class="form-label">Email</label>
        <input type="email" class="form-control" id="em_ail" name="c_mail">
      </div>
      <div class="col-md-6">
        <label for="inputPassword4" class="form-label">Password</label>
        <input type="password" class="form-control" id="inputPassword4" name="c_pass">
      </div>
      <div class="col-md-6">
        <label for="">Phone Number</label>
        <input type="number" class="form-control" id="inputNumber4" name="nub">
      </div>
      <div class="col-12">
        <label for="inputAddress" class="form-label">Address</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St" name="c_address">
      </div>
      <div class="col-md-4">
        <label for="">Gender</label><br>
        <input type="radio" name="gender" value="male">
        <label for="">male</label><br>
        <input type="radio" name="gender" value="female">
        <label for="">female</label><br>
      </div>
      <div class="col-12">
        <button type="submit" class="btn btn-primary">Sign in</button>
      </div>
    </form>
  </div>
  <script>
    $('#em_ail').change(function () {
      $.ajaxSetup({
        headers: {
          "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val() //passing csrf token in ajax request
        }
      })
      $.ajax({ 
        url: '{% url "common:check_email" %}', //url in which ajax call is made
        type:'POST', //methode in which data is send

        data: {
          email: $(this).val() //here key is 'email'
        },
        success: function (response){

          console.log(response.status)
          if (response.status == true)
            alert('email already exist can not use')
        }

      })
    })
  </script>
</body>

</html>

common/templates/common/project_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/pro.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
  <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"
        style="color: darkcyan;"><b><i>VIVLIOGRAFIA</i></b></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#" style="color: white;">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#" style="color: white;">About </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="" style="color: white;">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'common:sellersu' %}" style="color: white;">Creat seller account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'common:cuslog' %}" style="color: white;">Login </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'common:seller' %}" style="color: white;">Seller</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="div1">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
          aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
          aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
          aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'images/bg.jpg' %}" class="d-block w-100" alt="..." style="height: 500px; width: 100%;">
          <div class="carousel-caption d-none d-md-block">
            <h5>First slide label</h5>
            <p>Some representative placeholder content for the first slide.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'images/bg.jpg' %}" class="d-block w-100" alt="..." style="height: 500px; width: 100%;">
          <div class="carousel-caption d-none d-md-block">
            <h5>Second slide label</h5>
            <p>Some representative placeholder content for the second slide.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'images/bg.jpg' %}" class="d-block w-100" alt="..." style="height: 500px; width: 100%;">
          <div class="carousel-caption d-none d-md-block">
            <h5>Third slide label</h5>
            <p>Some representative placeholder content for the third slide.</p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  <div class="row">
    <b class="text-center"> PRODUCTS</b>
 {% for product in products %}
 <div class="col-3 ms-4 p-2" style="overflow: hidden;">
   <div class="card" style="width: 18rem; height: 18rem;">
     <a href=""><img src="{{product.product_image.url}}" class="card-img-top" alt="..."
         style="width:90px; height:90px;"></a>
     <div class="card-body p-3">
       <h5 class="card-title" style="margin-bottom: 0;">{{product.product_name|title}}</h5>
       <h2 style="margin-bottom: 0;">Rs.{{product.product_price}}</h2>
       <!-- <p class="card-text" style="margin-bottom: 0;">{{product.product_discription}}</p> -->
       <p class="card-text" style="margin-bottom: 0;">seller:{{product.seller.seller_name}}</p>
       <a href="{% url 'customer:pro_details' product.id %}" class="btn btn-primary"
         style="text-decoration: none;">details</a>
     </div>
   </div>
 </div>
 {% endfor %}

</div>

<footer id="foot_er">
  <div class="row">
    <div class="col-md-3">
      <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a> <br><br>
      <a class="nav-link" href="" style="color: aliceblue;"><b>contact</b></a><br><br>
      <a class="nav-link" href="" style="color: aliceblue;"><b>email@gamil.com</b></a>
    </div>
    <div class="col-md-3">
      <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a>
    </div>
    <div class="col-md-3">
      <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a>
    </div>
  </div>

</footer>
</body>

</html>

common/templates/common/seller_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/sell.css' %}">
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"></script>
</head>
<body>
    <div>
        <header class="text-center "><h1> SELLER LOGIN</h1></header>
    </div>
    <div class="container p-4">
      <a href="{% url 'common:prohome' %}" style="padding-left: 90%;"><button class="btn-danger"><--HOME--></button></a>
    <div class="sell p-4">
        <form method="POST">
          {% csrf_token %}
          {{msg}}
            <div class="mb-3">
              <!-- <label for="exampleInputEmail1" class="form-label">User name</label> -->
              <input type="name" name="u_name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="username">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
              <!-- <label for="exampleInputPassword1" class="form-label">Password</label> -->
              <input type="password" name="pass" class="form-control" id="exampleInputPassword1" placeholder="password">
            </div>
            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button><br>
            <span>sign up if you don't have an account</span><a href="{% url 'common:sellersu' %}">sign up</a>
          </form>
    </div>
  </div>
</body>
</html>

common/templates/common/seller_signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>seller signup</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
  <div class="text-center p-4">
    <h1>SELLER SIGNUP</h1>
  </div>

  <div class="container bg-success">
    <br>
    <div class="col-md-6 p-4">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label for="" class="form-label text-light">SELLER NAME</label>
          <input type="name" name="s_name" class="form-control" id="">
        </div>

        <div class="mb-3">
          <label for="" class="form-label text-light">ADDRESS </label> <br>
          <textarea name="s_address" id="" cols="30" rows="5" style="width: 400px; border-radius: 10px;"></textarea>
        </div>

        <div class="row g-3 align-items-center mb-3">
          <div class="col-auto">
            <label for="" class="form-label text-light">PHONE NUMBER</label>
          </div>
          <div class="col-auto">
            <input type="number" name="s_phone" class="form-control" id="">
          </div>

        </div>

        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label text-light">EMAIL</label>
          <input type="email" name="s_email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
          <div id="emailHelp" class="form-text"></div>
        </div>

        <div class="mb-3">
          <label for="" class="form-label text-light">COMPANY NAME</label>
          <input type="text" name="s_companyname" class="form-control" id="" aria-describedby="">
          <div id="" class="form-text"></div>
        </div>

        <div class="mb-3">
          <label for="" class="form-label text-light">ACCOUNT HOLDER NAME</label>
          <input type="text" name="s_accholdername" class="form-control" id="" aria-describedby="">
          <div id="" class="form-text"></div>
        </div>

        <div class="row g-3 align-items-center mb-3">
          <div class="col-auto">
            <label for="" class="form-label text-light">IFSC CODE</label>
          </div>
          <div class="col-auto">
            <input type="text" name="s_ifsc" class="form-control" id="" aria-describedby="">
          </div>
          <div id="" class="form-text"></div>
        </div>

        <div class="row g-3 align-items-center mb-3">
          <div class="col-auto">
            <label for="" class="form-label text-light">BRANCH &nbsp;&nbsp;</label>
          </div>
          <div class="col-auto">
            <input type="text" name="s_branch" class="form-control" id="" aria-describedby="">
          </div>

          <div id="" class="form-text"></div>
        </div>

        <div class="mb-3">
          <label for="" class="form-label text-light">BANK ACCOUNT NUMBER</label>
          <input type="number" name="s_accnumber" class="form-control" id="">
        </div>


        <div class="row g-3 align-items-center">

          <label for="" class="col-form-label text-light">FILE UPLODE</label>
          <input type="file" name="s_file" id="" class="form-control" aria-describedby="">

        </div> <br>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label text-light" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary" style="
                color: white;
                height: 40px;
                width: 250px;
                border: none;
                border-radius: 50px;
                box-shadow: 5px 5px 5px rgb(189, 189, 189);">Submit</button>
      </form>
    </div>
  </div>

</body>

</html>