common/urls.py
from django.urls import path

from . import views

app_name = 'common'
urlpatterns=[
    path('pjt_home',views.p_home,name='prohome'),
    path('cust_login',views.c_home,name='cuslog'),
    path('c_signup',views.c_signup,name='custsp'),
    path('seller_login',views.s_home,name='seller'),
    path('seller_signin',views.s_signin,name='sellersu'),
    path('exist_email',views.email_exist,name='check_email'),
    

]

customer/urls.py
from django.urls import path
from .import views

app_name='customer'
urlpatterns=[
    path('c_home',views.cust_home,name='customer_home'),
    path('profile',views.my_profile,name='myprofile'),
    path('list',views.cat,name='cat_l'),
    path('logout',views.log_out,name='logout_cust'),
    path('ch_pass',views.changepass_cust,name='c_custpass'),
    path('p_detail/<int:pid>',views.product_detail,name='pro_details'),
    path('mycart',views.my_cart,name='cart'),
    path('order',views.my_order,name='myorder'),
    path('remove_cart/<int:pid>',views.remove_item,name='remove_cart'),
    path('master',views.master,name='master'),
    path('purchase/<int:pid>',views.purchase,name='purchase')
    

]

ecommers/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include('common.urls')),
    path('ecom_admin/',include('ecome_admin.urls')),
    path('seller/',include('sellerpage.urls')),
    path('customer/',include('customer.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sellerpage/urls.py
from django.urls import path
from .import views

app_name='sellerpage'

urlpatterns=[
    path('sellerhome',views.sl_h,name='sellerhome'),
    path('products',views.add_pro,name='addproduct'),
    path('catalog',views.cato_log,name='productcatolog'),
    path('changepassword',views.change_pass,name='c_password'),
    path('history',views.od_history,name='o_history'),
    path('recent',views.r_history,name='recent_history'),
    path('update',views.s_update,name='update_stock'),
    path('logout',views.log_out,name='logout_cust'),
    path('sell_profile',views.proff,name='profile'),
    path('get_stock',views.get_stock,name='up_stock'),
    
]

sellerpage/models.py
from django.db import models
from common.models import Seller

# Create your models here.

class Product(models.Model):
    seller = models.ForeignKey(Seller,on_delete=models.CASCADE)
    product_name = models.CharField(max_length=70)
    product_discription = models.CharField(max_length=800,default='')
    product_number = models.BigIntegerField()
    product_catogari = models.CharField(max_length=20,default='')
    product_stock = models.IntegerField()
    product_price = models.FloatField()
    product_image = models.ImageField(upload_to="product")

sellerpage/views.py
from django.shortcuts import render, redirect
from common.models import Seller
from .models import Product
from django.http import JsonResponse
from .auth_gaurd import auth_seller


# Create your views here.

@auth_seller
def sl_h(request):
    product_list = Product.objects.all()
    seller_data = Seller.objects.get(id=request.session['seller'])
    return render(request, 'sellerpage/seller_home.html', {'data': seller_data,'products': product_list})

@auth_seller
def add_pro(request):
    seller_data = Seller.objects.get(id=request.session['seller'])
    msg = ''
    if request.method == 'POST':
        product_name = request.POST['p_name']
        product_discription = request.POST['p_dis']
        product_number = request.POST['p_no']
        product_catogary = request.POST['catogary']
        product_price = request.POST['p_price']
        product_stock = request.POST['P_stock']
        product_image = request.FILES['p_file']

        new_product = Product(

            product_name=product_name,
            product_discription=product_discription,
            product_number=product_number,
            product_catogari=product_catogary,
            product_stock=product_stock,
            product_price=product_price,
            product_image=product_image,
            seller_id=request.session['seller']

        )
        new_product.save()
        msg = 'product added sucessfully'
    return render(request, 'sellerpage/add_product.html', {'msg': msg, 'data': seller_data})

@auth_seller
def cato_log(request):
    seller_data = Seller.objects.get(id=request.session['seller'])
    seller_products = Product.objects.filter(seller=request.session['seller'])
    return render(request, 'sellerpage/catalog_seller.html', {'products': seller_products, 'data': seller_data})

@auth_seller
def change_pass(request):
    seller_data = Seller.objects.get(id=request.session['seller'])
    msg = ''
    if request.method == 'POST':
        seller = Seller.objects.get(id=request.session['seller'])

        current_pass = request.POST['cur_pass']
        new_pass = request.POST['new_pass']
        confirm_pass = request.POST['conf_pass']

        if seller.seller_password == current_pass:

            if new_pass == confirm_pass:
                # Seller.objects.filter( ).update(current_pass = new_pass)
                seller.seller_password = new_pass
                seller.save()
                msg = 'password change successfully'

            else:
                msg = 'password does not match'

        else:
            msg = 'incorect password'
        
    context = {
        'msg': msg,
        'data': seller_data,
    }
    return render(request, 'sellerpage/change_password.html', context)

@auth_seller
def od_history(request):
    seller_data = Seller.objects.get(id=request.session['seller'])
    return render(request, 'sellerpage/order_history.html', {'data': seller_data})

@auth_seller
def r_history(request):
    seller_data = Seller.objects.get(id=request.session['seller'])
    return render(request, 'sellerpage/recent_history.html', {'data': seller_data})

@auth_seller
def s_update(request):
    msg = ''
    seller_data = Seller.objects.get(id=request.session['seller'])

    product_stock = Product.objects.filter(seller=request.session['seller'])
    if request.method == 'POST':
        new_stock = request.POST['new_stock']
        product_id = request.POST['pro_id']

        product = Product.objects.get(id=product_id)

        product.product_stock = product.product_stock + int(new_stock)
        product.save()
        msg = '!!!!!!!!!!!!!!! stock updated !!!!!!!!!!!!'
        

    return render(request, 'sellerpage/update_stock.html', {'data_stock': product_stock, 'data': seller_data,'msg':msg})

@auth_seller
def log_out(request):
    del request.session['seller']
    request.session.flush()  # to remove session from django_session table
    return redirect('common:prohome')

@auth_seller
def proff(request):
    seller_data = Seller.objects.get(id=request.session['seller'])
    return render(request, 'sellerpage/profile.html', {'data': seller_data})

@auth_seller
def get_stock(request):
    id = request.POST['id']
    product = Product.objects.get(id=id)
    product_name = product.product_name
    current_stock = product.product_stock
    p_id = product.id
    return JsonResponse({'pro_name': product_name, 'stock': current_stock, 'pr_id': p_id})

sellerpage/templates/sellerpage/add_product.html
{% extends 'sellerpage/seller_home.html' %}

{% block content %}

{% load static %}
<div>
  <h1 class="text-center">ADD PRODUCTS</h1>
</div>
<div style="background-color: rgb(113, 223, 172); height: 550px;" >
  <div class="div1 mt-5 ms-5 p-4">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{msg}}
      <div class="mb-3">
        <label for="" class="form-label">PRODUCT NAME </label>
        <input type="text" name="p_name" class="form-control" id="" aria-describedby="">
      </div>
      <div class="mb-3">
        <label for="" class="form-label">PRODUCT CATOGARY</label>
        <select name="catogary" id="">
          <option value="books">books</option>
          <option value="movies">movies</option>
          <option value="games">games</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="" class="form-label">PRODUCT PRICE</label>
        <input type="number" name="p_price" class="" id="">
      </div>
      <div class="mb-3">
          <label class="form-check-label" for="exampleCheck1">PRODUCT NUMBER</label>
        <input type="number" name="p_no" class="form-control" id="">
      </div>
      <div class="mb-3">
      <label class="form-check-label" for="exampleCheck1">PRODUCT DISCRIPTION</label>
      <input type="textarea" name="p_dis" class="form-control" id="">
      </div>
      <div class="mb-3">
          <label class="form-check-label" for="exampleCheck1">CURRENT STOCK</label>
        <input type="number" name="P_stock" class="" id="">
      </div>
      <div>
        <label for="" class="col-form-label text-light">FILE UPLODE</label>
        <input type="file" name="p_file" id="" class="form-control" aria-describedby="">
      </div> <br>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

  {% endblock %}

sellerpage/templates/sellerpage/catalog_seller.html
{% extends 'sellerpage/seller_home.html' %}

{% block content %}

{% load static %}

<div class="row">

    {% for product in products %}
    <div class="col-3 ms-4 p-3">
        <div class="card" style="width: 18rem; height: 22rem;">
            <a href=""><img src="{{product.product_image.url}}" class="card-img-top" alt="..." style="width:200px; height:200px;"></a>
            <div class="card-body">
                <h5 class="card-title">{{product.product_name|title}}</h5>
                <h2>Rs.{{product.product_price}}</h2>
                <!-- <p class="card-text" style="overflow: hidden;">{{product.product_discription}}</p> -->

                <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
            </div>
        </div>
    </div>
    {% endfor %}

</div>


{% endblock %}

sellerpage/templates/sellerpage/change_password.html
{% extends 'sellerpage/seller_home.html' %}

{% block content %}

{% load static %}

<div>
    <header class="text-center ">
        <h1>CHANGE PASSWORD</h1>
    </header>
</div>
<div class="container p-4">
    <div class="cust p-4">
        <form method="POST">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">CURENT PASSWORD</label>
                <input type="text" name="cur_pass" class="form-control" id="exampleInputEmail1"
                    aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">NEW PASSWORD</label>
                <input type="text" name="new_pass" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">CONFROM PASSWORD</label>
                <input type="text" name="conf_pass" class="form-control" id="exampleInputPassword1">
            </div>
           <div>
            <button type="submit" class="btn btn-primary">SET PASSWORD</button><br>
           </div>
            {{msg}}
        </form>
    </div>
</div>


{% endblock %}

sellerpage/templates/sellerpage/order_history.html
<!-- {% extends 'sellerpage/seller_home.html' %} -->

{% block content %}

{% load static %}

<div class="text-center admin_nmae">
    <h3 style="padding-left: 50px; padding-top: 10px;color:rgb(13, 13, 13);text-align: center;" ><b><i>SELLER NAME</i></b></h3>
</div>
<div class="row" style="flex: content;">
    <div class="col-md-9" style="width:300px">
        <img src="{% static 'images/0x0.jpg' %}" class=" " alt="" style="width: 200px;
        height: 200px;
        padding-top: 50px;">
        
    </div>
    <div class="" style="background-color: blue;width: 200px;
    height: 200px;
    padding-top: 50px;">
        
    </div>
</div>


{% endblock %}

sellerpage/templates/sellerpage/profile.html
{% block content %}

{% load static %}

<div  style="padding-left: 100PX;">

    <header class="" style="text-align: center;">
        <h1>PROFILE</h1>
        <h3>wellecome to profile {{data.seller_name}}</h3>
    </header>
    <a href=""><img src="{{data.seller_pic.url}}" class=" " alt="" style="width: 120px;
        height: 120px;
        padding-top: 10px;"></a><br>
    <span>change profile photo</span><br><br>
    <a href="{% url 'sellerpage:sellerhome' %}" style="padding-left: 0px;"><button>back</button></a><br><br>

    <div>
        
        <label for="" class="col-form-label text-light">PHOTO UPLODE</label>
        <input type="file" name="s_file" id="" class="form-control" aria-describedby=""><br><br>
        <a href="" class="lio" style="text-decoration: none; color:black"><b>NAME:{{data.seller_name}}</b></a><br><br>
        <a href="" class="lio" style="text-decoration: none; color:black"><b>EMAIL:{{data.seller_email}}</b></a><br><br>
        <a href="" class="lio" style="text-decoration: none; color:black"><b>ADDRESS:{{data.seller_addres}}</b></a><br><br>
        <a href="{% url 'sellerpage:sellerhome' %}" class="li0" style=" text-decoration: none;
                color: rgb(15, 15, 15);">HOME</a><br><br>



    </div> <br>




</div>
{% endblock %}

sellerpage/templates/sellerpage/seller_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>seller_home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src=" https://code.jquery.com/jquery-3.6.1.js"
        integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous">
        </script>
</head>

<body>
    <nav class="navbar navbar-expand-lg " style="background-color: rgb(59, 59, 159);">
        <div class="container-fluid">
            <a class="navbar-brand" href="#" style="color: rgb(49, 213, 213);"><b><i>VIVLIOGRAFIA</i></b></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mr-auto" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" style="color: beige;" aria-current="page"
                            href="{% url 'sellerpage:sellerhome' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" style="color: beige;"
                            href="{% url 'sellerpage:profile' %}">profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" style="color: beige;" href="{% url 'sellerpage:addproduct' %}"">add product</a>
                    </li>
                    <li class=" nav-item">
                            <a class="nav-link active" style="color: beige;"
                                href="{% url 'sellerpage:productcatolog' %}">catelog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" style="color: beige;" href="{% url 'sellerpage:c_password' %}">change
                            password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" style="color: beige;"
                            href="{% url 'sellerpage:o_history' %}">orderhistory</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" style="color: beige;"
                            href="{% url 'sellerpage:update_stock' %}">update stocks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" style="color: beige;"
                            href="{% url 'sellerpage:recent_history' %}">recent history</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" style="color: beige;"
                            href="{% url 'sellerpage:logout_cust' %}">logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- <div class="col-md-10"> -->


    {% block content %}

    <div class="text-center">
        <h1><i>wellcome {{data.seller_name}}</i></h1>
    </div>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/hp.jpg' %}" class="d-block w-100" alt="..."
                    style="height: 500px; width: 100%;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Some representative placeholder content for the first slide.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/z.jpg' %}" class="d-block w-100" alt="..."
                    style="height: 500px; width: 100%;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Some representative placeholder content for the second slide.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/spm.jpg' %}" class="d-block w-100" alt="..."
                    style="height: 500px; width: 100%;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Some representative placeholder content for the third slide.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="row">
        <b class="text-center"> PRODUCTS</b>
        {% for product in products %}
        <div class="col-3 ms-4 p-2">
            <div class="card" style="width: 18rem; height: 18rem;">
                <a href=""><img src="{{product.product_image.url}}" class="card-img-top" alt="..."
                        style="width:90px; height:90px;"></a>
                <div class="card-body p-3" style="overflow: hidden;">
                    <h5 class="card-title" style="margin-bottom: 0;">{{product.product_name|title}}</h5>
                    <h2 style="margin-bottom: 0;">Rs.{{product.product_price}}</h2>
                    <!-- <p class="card-text" style="margin-bottom: 0; overflow: hidden;">{{product.product_discription}}</p> -->
                    <p class="card-text" style="margin-bottom: 0;">seller:{{product.seller.seller_name}}</p>
                    <!-- <a href="{% url 'customer:pro_details' product.id %}" class="btn btn-primary"
                        style="text-decoration: none;">detail</a> -->
                </div>
            </div>
        </div>
        {% endfor %}

    </div>

    {% endblock %}
    </div>
    </div>
    <footer id="foot_er" style="background-color: black;">
        <div class="row">
            <div class="col-md-3">
                <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a> <br><br>
                <a class="nav-link" href="" style="color: aliceblue;"><b>contact</b></a><br><br>
                <a class="nav-link" href="" style="color: aliceblue;"><b>email@gamil.com</b></a>
            </div>
            <div class="col-md-3">
                <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a>
            </div>
            <div class="col-md-3">
                <a class="nav-link" href="" style="color: aliceblue;"><b>About</b></a>
            </div>
        </div>

    </footer>
</body>

</html>

sellerpage/templates/sellerpage/update_stock.html
{% extends 'sellerpage/seller_home.html' %}

{% block content %}

{% load static %}
<div>
    <h1 class="text-center"></h1>
</div>
<div style="background-color: rgb(113, 223, 172); height: 550px;">
    <div class="div1 mt-5 ms-5 p-4">
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" id="p_id" name="pro_id"><br><br>
            <div class="mb-3">
                <label class="form-check-label" for="exampleCheck1">PRODUCT NUMBER</label>
                <select name="product_no" id="p_no" aria-placeholder="product number">
                    <option disabled selected>select product</option>
                    {% for product in data_stock %}
                    <option value="{{product.id}}">{{product.product_number}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="" class="form-label">PRODUCT NAME </label>
                <input type="text" name="p_name" class="form-control" readonly id="pr_name" aria-describedby="">
            </div>
            <div class="mb-3">
                <label for="" class="form-label">CURRENT STOCK </label>
                <input type="text" name="p_stock" class="form-control" readonly id="c_stock" aria-describedby="">
            </div>
            <div class="mb-3">
                <label class="form-check-label" for="exampleCheck1">NEW STOCK</label>
                <input type="number" name="new_stock" class="" id="n_stock">
            </div>
            <button type="submit" class="btn btn-primary">UPDATE</button><br>
            {{msg}}
        </form>
    </div>

</div>
<script>
    $('#p_no').change(function () {
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
            }
        })
        $.ajax({
            url: '{% url "sellerpage:up_stock" %}',
            type: 'POST',

            data: {
                id: $(this).val()
            },
            success: function (response) {

                console.log(response.pro_name)
                console.log(response.stock)
                $('#pr_name').val(response.pro_name)
                $('#c_stock').val(response.stock)
                $('#p_id').val(response.pr_id)
            }

        })
    })
</script>

{% endblock %}